### ISSUE TITLE
[Request] Regarding how widgets are focused

### ISSUE THREAD

**Issue by rizreflects** [heppen7/skin.cosmic#12]
Lets say for example I am in the movies section on the homescreen. I then scroll down by 3 widgets. If i leave the movies section and go to TV shows for example, those widgets will have also moved down by 3. Therefore what I'm asking is, would it be possible to make the widgets automatically focus onto the first widget each time I enter that particular section?

**Comment by nfm886** [comment]
I will improve it soon... There is also bug when moving through widgets so maybe it's causing your "issue".

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
