### ISSUE TITLE
[BUG] Trailers not working properly with TheOath

### ISSUE THREAD

**Issue by ViewAfterReview** [heppen7/skin.cosmic#26]
Skin Version: 1.0.25

Playing trailers in the background in vertical view always play a random trailer. If I am right it always plays the latest trailer that was added. 
I would really appreciate it if you could fix this issue!

**Comment by nfm886** [comment]
Could you please record a screen how it works? 
I don't use TheOath add-on. It would help investigate the issue. Thanks.

**Comment by ViewAfterReview** [comment]
Thanks for looking out for this. This is the video you requested

https://user-images.githubusercontent.com/86300945/131227664-ee2eca92-ddcc-4caa-976f-3e254ae540d0.mp4

**Comment by nfm886** [comment]
Hmm...
Did you try other sources like TMDbHelper widget for example?

**Comment by ViewAfterReview** [comment]
TMDB works but info on the left are hidden when trailer play except title, like the video above

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
