### ISSUE TITLE
[Request] Support Next Page on Widgets

### ISSUE THREAD

**Issue by prazsky** [heppen7/skin.cosmic#46]
Current behavior is when you reach the end of a list, you can enable a "Next Page" button which will drop you into TMDbH. It'd be real nice if there was some way to either auto-load more items in the list or on hitting Next Page they are loaded into the same list allowing for more scrolling UI

**Comment by tundrablasen** [comment]
+1

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
