### ISSUE TITLE
[Bug] Watched indicators

### ISSUE THREAD

**Issue by rizreflects** [heppen7/skin.cosmic#63]
Currently the indicators only show if you hover over that particular movie / TV show.. see the picture below:

![IMG_20210914_155202.jpg](https://user-images.githubusercontent.com/76912707/133280965-069f82ec-3863-45b3-8307-334a56a981f1.jpg)

But could you make this so the indicators are always showing, even for items that aren't focused? For example, in the picture I sent, Rick and Morty should also have the watched indicator, but it doesn't show until I hover over it.

**Comment by nfm886** [comment]
It does not show in Flixed scrolling. If you disable it, it will show for all items.

**Comment by rizreflects** [comment]
I don't have flixed scrolling enabled as you can see here

![IMG_20210914_163018.jpg](https://user-images.githubusercontent.com/76912707/133287561-c0e1c508-8338-4f57-b1c3-092ac4381b99.jpg)

**Comment by nfm886** [comment]
> I don't have flixed scrolling enabled as you can see here
> 
> ![IMG_20210914_163018.jpg](https://user-images.githubusercontent.com/76912707/133287561-c0e1c508-8338-4f57-b1c3-092ac4381b99.jpg)

Oh well. That sounds like a bug then :P

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
