### ISSUE TITLE
Fanart darkened in vertical view

### ISSUE THREAD

**Issue by rizreflects** [heppen7/skin.cosmic#64]
Since the last update the fanart has gone very dark when scrolling on the homepage. I see you darkened the flix view (which looks really good btw, the more information page looks amazing) however in doing so I think you accidently darkened the fanart even when not in flix view. Just thought I'd point it out to you in case you overlooked it.

**Comment by nfm886** [comment]
Hey,
Could you please show me a screenshot?

**Comment by rizreflects** [comment]
Increasing the homescreen alpha fixed the problem. 

Here was the problem anyway:

Before update-
![IMG_20210915_211826.jpg](https://user-images.githubusercontent.com/76912707/133503822-2594101b-0ec3-4391-9a40-4d380aff314d.jpg)

After update-
![IMG_20210915_211854.jpg](https://user-images.githubusercontent.com/76912707/133503858-d822a0f1-f153-494c-bf51-d332085c54cb.jpg)

That being said, increasing the alpha on homescreen also changes the brightness in flix view.. could you make a separate alpha for flix view maybe? Reason being, you can't really read the text when the brightness is too high.. see here:

![IMG_20210915_212233.jpg](https://user-images.githubusercontent.com/76912707/133504053-cfd26742-b54d-40fb-81e8-8b4507c24c7a.jpg)

Very difficult to read.

**Comment by rizreflects** [comment]
Sorry I mean flix spotlight* not flix view

**Comment by rijsab** [comment]
Yeah, text and selected button is also difficult to read when trailer is playing, so alpha is not going to tackle this. :)

**Comment by nfm886** [comment]
> Increasing the homescreen alpha fixed the problem.
> 
> Here was the problem anyway:
> 
> Before update-
> ![IMG_20210915_211826.jpg](https://user-images.githubusercontent.com/76912707/133503822-2594101b-0ec3-4391-9a40-4d380aff314d.jpg)
> 
> After update-
> ![IMG_20210915_211854.jpg](https://user-images.githubusercontent.com/76912707/133503858-d822a0f1-f153-494c-bf51-d332085c54cb.jpg)
> 
> That being said, increasing the alpha on homescreen also changes the brightness in flix view.. could you make a separate alpha for flix view maybe? Reason being, you can't really read the text when the brightness is too high.. see here:
> 
> ![IMG_20210915_212233.jpg](https://user-images.githubusercontent.com/76912707/133504053-cfd26742-b54d-40fb-81e8-8b4507c24c7a.jpg)
> 
> Very difficult to read.

Actually second alpha value should apply to Flix spotlight. I will look into it tomorrow.

**Comment by nfm886** [comment]
> Yeah, text and selected button is also difficult to read when trailer is playing, so alpha is not going to tackle this. :)

I have an idea what to do with it :)

**Comment by rijsab** [comment]
For sure you know what you are doing my friend :D

**Comment by rizreflects** [comment]
Really appreciate your work. Your skin has changed my entire Kodi experience. Thanks a lot

**Comment by nfm886** [comment]
> Yeah, text and selected button is also difficult to read when trailer is playing, so alpha is not going to tackle this. :)

I made a "shadow spot" for Flix Spotlight (1st level) to increase readability. Please test it: https://github.com/nfm886/skin.cosmic/commit/1390d8666148c5e1f0ffb2aef4522bf901143a35
I will improve it and also add for next levels. What you think guys? Is it good solution? ;) It just a preview before release to hear a feedback.

**Comment by rizreflects** [comment]
Sorry for not responding sooner, I'm back at university now so I get a bit busy. That being said, i can't seem to find the option for the spotlight shadow. Isit under the background section in skin settings?

**Comment by nfm886** [comment]
There is no setting for it. It should apply automatically when full screen trailers are enabled. If you have not enabled full screen trailer, there is no shadows because it's not necessary :)

**Comment by rizreflects** [comment]
Ah I see.. I dont enable trailers as it's very slow to load on my Nvidia shield.. I thought you were referring to this ![IMG_20210928_134056.jpg](https://user-images.githubusercontent.com/76912707/135088885-e08fe523-2e99-4cc3-a424-e7dbde9347b2.jpg)

Tbh I assumed the trailer function wasn't working correctly because if set to manual, the trailers always play in fullscreen whether I have the option enabled or not.

**Comment by nfm886** [comment]
Oh well. Thanks for pointing this out. I did not check it under Classic layout.
Under Vertical it looks like that: https://imgur.com/JcJ4ShS so it's blur there. And this blur is gone when you are leaving 2nd level of Flix Spotlight.

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
