### ISSUE TITLE
[BUG] Missing Checkboxes

### ISSUE THREAD

**Issue by BinaryAssault** [heppen7/skin.cosmic#67]
I use auto widget as part of my skin setup. Part of auto widget allows you to define multiple paths. When selecting an auto widget inside of a widget in cosmic, the portion where you select your paths has Checkboxes. But in cosmic they're not there. But they act like they are. I can click and hear it doing stuff. I'm assuming this is just a color adjustment but haven't had time to play around. 

To replicate:
Create an auto widget with multiple paths
Add new widget to skin via cosmic 
When selecting the auto widget in the widget selection menu, select cycling
Select random path
On the next window notice the not visible Checkboxes. 

I believe this is a skin issue as other skins show the Checkboxes with the same steps applied.

**Comment by rijsab** [comment]
Do you mean the highlited items not visible? I know they are hard to see but if you watch closely you will see a brighter white colour when selected. 

@nfm886 you can see in Kodi System settings, under whitelist. If you select screen resolution it is quite difficult to see which items have been selected. Same issue as for above described but in another settting.

**Comment by BinaryAssault** [comment]
> Do you mean the highlited items not visible? I know they are hard to see but if you watch closely you will see a brighter white colour when selected.
> 
> @nfm886 you can see in Kodi System settings, under whitelist. If you select screen resolution it is quite difficult to see which items have been selected. Same issue as for above described but in another settting.

It's not there from what I can see. An ever easier way to replicate it is to go to cosmic settings and go to the cosmic list item. Toggle debugging checkbox can be seen but is functional. I tried playing with colors and its still not there.

**Comment by nfm886** [comment]
Hi,
Could you please attach an image? Would be awesome.

> An ever easier way to replicate it is to go to cosmic settings and go to the cosmic list item. Toggle debugging checkbox can be seen but is functional.

It's not a radio button, it's a normal button. That's why checkbox is not there :)

**Comment by BinaryAssault** [comment]
> Hi,
> Could you please attach an image? Would be awesome.
> 
> > An ever easier way to replicate it is to go to cosmic settings and go to the cosmic list item. Toggle debugging checkbox can be seen but is functional.
> 
> It's not a radio button, it's a normal button. That's why checkbox is not there :)

Sure, you can see an example here. There is no way to depict that debugging is active or not. This isn't just debugging though, this is true for many controls in the skin for me.

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
