### ISSUE TITLE
[Bug] Trailers continously replay

### ISSUE THREAD

**Issue by BinaryAssault** [heppen7/skin.cosmic#68]
I noticed that if you have trailers enabled and one kicks off, it will auto-replay if you exit the trailer before the trailer completes. 

To replicate:
Enable trailers
Hover over a widget
Wait for the trailer to start
Stop the trailer manually
Wait for the trailer to restart.

**Comment by nfm886** [comment]
Thanks. Someone mentioned it before. I will try to fix it today :)

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
