### ISSUE TITLE
[REQUEST] Embuary Helper widget labels

### ISSUE THREAD

**Issue by rijsab** [heppen7/skin.cosmic#70]
Hi,

Embuary Helper features, such as Based on Last Watched Items, do not show the labels in Widget name. So difficult to understand On which Last Item the widget list is based on. However accessing this feature through Embuary Helper addon it is possible to see as it is mentioning for example.. Based on last watched item Game of Thrones. Currently Game of Thrones is missing in Widget name. 

Would be great to have this implemented in the skin as it is a dependency. 

Thanks.

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
