### ISSUE TITLE
[Bug] Very slow start times

### ISSUE THREAD

**Issue by BinaryAssault** [heppen7/skin.cosmic#72]
I noticed that anytime I reboot my HTPC, the cosmic skin takes 1-3 minutes to boot before anything works. Besides navigating the menu, nothing really works until whatever finishes processing exits. By nothing really works, I mean local library search doesn't work, no add-ons can be used and most widgets won't load. 

Whatever is happening on startup in the background is blocking everything else from being started. What that is, I am not sure. 

The issue seems to be caused by the cosmic skin (I absolutely love this skin btw, it's by far the best I've used). I swapped back to artic zephyr reloaded with a very similar widget load out and it loads immediately under the same circumstances. 

Although I don't know how skins and Kodi really work for loading, I will take a look into the code and see if I find anything intriguing. I took a debug log, but the amount of data in that log for a 3 minute time frame is mind boggling. 

To add, I disabled any addon used for widgets and that didn't affect the slow load times. Next step is a wipe of Kodi if anyone can't find anything. Maybe it got gunked up

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
