### ISSUE TITLE
Extra art option+Blur mode in Home

### ISSUE THREAD

**Issue by Whiteripd0** [heppen7/skin.cosmic#74]
Thanks a lot for this skin) I really like the "Spotlight" view and also use the "Vertical" view, but I also really like the "Horizontal" view you are working on right now .. I wanted to know about two features that I really like:  1) Blur mode (similar to Arctic Zephyr,left change colors) 2) Extra art option (fan art rotation) Thanks a lot in advance!

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
