### ISSUE TITLE
Show channel name when switching channels

### ISSUE THREAD

**Issue by linuxissuper** [heppen7/skin.cosmic#76]
When I'm already watching TV and I want to switch a channel with up and down buttons    
I don't know what is the current channel and what the next.
![image](https://user-images.githubusercontent.com/74221543/136538465-26fe231f-e533-469d-8743-7c2058efdf11.png)

I would prefer something like this:
![image](https://user-images.githubusercontent.com/74221543/136538524-e82ba449-f920-4a19-9fe2-9f7cb0696346.png)

Or maybe show the channel name and logo also on the OSD from the first screenshot

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
