### ISSUE TITLE
Cosmic skin breaks Rising Tides addon

### ISSUE THREAD

**Issue by gcores** [heppen7/skin.cosmic#81]
When using the Cosmic skin, pressing the links for the games in the Rising Tides addon does nothing. 
If I change to a different skin, everything works again.

I am using Kodi 19.3 in a chromecast with google TV device.

**Comment by nfm886** [comment]
Probably because you have enabled Flix spotlight. To make it working again you have to disable Flix spotlight in settings or at least disable triggering flix spotlight on select.

**Comment by gcores** [comment]
Flix Spotlight is not enabled.

**Comment by nfm886** [comment]
Ok. So it must be something deeper. Could you please provide me some screenshots with debugging enabled?

**Comment by gcores** [comment]
Here are two screenshots, one is before pressing the link and the other is after pressing the link.

![Screenshot_20211124-195424](https://user-images.githubusercontent.com/31708747/143306734-2dda187a-49ee-40ee-b026-62f5a3dc3c3e.png)
![Screenshot_20211124-195438](https://user-images.githubusercontent.com/31708747/143306743-baf8e9de-784f-43dd-967d-f7dc0922952f.png)

**Comment by nfm886** [comment]
Hmm... That's kind of weird since I did not touch this view so it should have default behavior to playing things.
I will see in free time if I can do anything with it.

**Comment by heppen7** [comment]
Overdone. Room for new issues after new update.
